### ISSUE TITLE
Missing msgs_and_srvs package

### ISSUE THREAD

**Issue by jbourne15** [MAPIRlab/gaden#1]
Correct me if I am wrong, but I think there is a missing package "msgs_and_srvs", which is required for the simulated_gas_sensor package.  Where might I find this?

**Comment by JGMonroy** [comment]
Hi jbourne15,
The "msgs_and_srvs" pkg is an old dependency that is no longer necessary. I've fixed the cmake and the package.xml to remove this. Yet, notice that you still need the "olfaction_msgs" as explained in the main readme.

Thanks for reporting!

**Comment by jbourne15** [comment]
Thanks!
