### ISSUE TITLE
map error

### ISSUE THREAD

**Issue by r-miko** [MAPIRlab/gaden#11]
Hello,

When I run the launch file gaden_player_demo.launch I get the error:

![screenshot from 2018-04-25 15-19-55](https://user-images.githubusercontent.com/32842219/39813133-1f1bd512-5387-11e8-8871-bb33e7dd89ec.png)

Thank you in advance for your help,
Rebecca

**Comment by hdino** [comment]
@r-miko I encounter the same problem. Did you find a solution?

**Comment by GUYING7** [comment]
@hdino
Hi,hdino! I encounter the same problem. Did you find a solution?

**Comment by JGMonroy** [comment]
GADEN_demo has not been replaced by /test_env folder with different test environments. All the new scenarios have been tested and launch files provided.

**Comment by velonSigs** [comment]
> Hello,
> 
> When I run the launch file gaden_player_demo.launch I get the error:
> 
> ![screenshot from 2018-04-25 15-19-55](https://user-images.githubusercontent.com/32842219/39813133-1f1bd512-5387-11e8-8871-bb33e7dd89ec.png)
> 
> Thank you in advance for your help, Rebecca

hi,how do you solve this problem? I also met this issue
