### ISSUE TITLE
GADEN wind flow

### ISSUE THREAD

**Issue by kynoali** [MAPIRlab/gaden#22]
Hi 
I am using Gaden for BS my project. I want to generate my own environment and then use the GADEN c++ filament node to generate plum in my own environment. I followed all the procedures given in the gaden tutorial. when I run preprocessing launch file it is neither giving me any error nor generating an environment.  I run the simulation for 6s to generate the wind file(.csv file) and got many files. i am unable to find the problem at which step I did wrong. Can any one help me please

**Comment by PepeOjeda** [comment]
Hello. I am afraid I would need more information to help you. Could you share the files that you are using, or at least the error message that you are getting?

Also, just to clarify, GADEN does not generate the airflow, only the dispersion of the gas. You are expected to provide the wind files generated with openfoam (or simscale, or whatever you use) as an input.

**Comment by kynoali** [comment]
#PepeOjeda
Thanks for response, i generated wind file using OpenFOAM and simscale.  here i am going to attach some screenshots 
terminal screen short 
![Screenshot from 2022-05-19 10-48-40](https://user-images.githubusercontent.com/106002619/169929944-08d5c844-4951-4b94-996f-174b35996c62.png)
Preprocessing launch file 
![Screenshot from 2022-05-24 09-04-32](https://user-images.githubusercontent.com/106002619/169930051-3398c77a-5fe8-4838-9a37-bc02a71a7904.png)
CAD models
![Screenshot from 2022-05-24 09-04-41](https://user-images.githubusercontent.com/106002619/169930124-40ee522b-a5fa-4bb8-9598-4ef18123db5f.png)

.CSV file (unable to upload whole file )
![image](https://user-images.githubusercontent.com/106002619/169930348-9d66f661-3dbc-498d-8def-a46465b4e4a9.png)

**Comment by PepeOjeda** [comment]
There is one mistake in the launch file. The output model parameter should be named "outlets_model_0", rather than "outlets_model_1".

Still, this should not be what the issue is about. If you are not getting any messages at all, there must be some issue while first parsing the environment models. Could you share the stl files with me so I can test this?

**Comment by kynoali** [comment]
Thanks sir, i send  .stl file and .CSV file on your email [Ojedamorala@hotmail.com]
