### ISSUE TITLE
GADEN preprocessing error - Segmentation fault

### ISSUE THREAD

**Issue by rafluq** [MAPIRlab/gaden#23]
I tried to run GADEN preprocessing on my test environment "wwt_plant" but it gives me an error. I run in Debug mode and it gave me a segmentation fault in line:
https://github.com/MAPIRlab/gaden/blob/86d09bbee02c43a365725f734408e6dcc14ff322/gaden_preprocessing/src/preprocessing.cpp#L617

This happens when I have meshed the objects with a resolution of 0.2 meters, but it is fine when the mesh has a resolution of 1 meter (test environment "wwt_plant2").

Do you know why? Thank you!

I have attached both environments folders in this WeTransfer link: https://we.tl/t-PgfYfQkJ8w

**Comment by PepeOjeda** [comment]
Hello. It seems like there is some problem with the wind simulation. 

The x coordinate of your environment environment goes from -16 to 16, but there are wind values recorded for points at -37 and more. Those points are outside the environment you have defined with the CAD models, so you get a segfault when processing them.

It's difficult for me to say what might have caused this. Maybe you have several versions of the 3D model that have different scale and have used another one for the simulation?
![Screenshot from 2022-10-17 09-59-43](https://user-images.githubusercontent.com/26406833/196122861-ac32435b-ba7e-4e3d-8f44-33cf2ccbc185.png)
![Screenshot from 2022-10-17 10-00-37](https://user-images.githubusercontent.com/26406833/196122863-86e59de5-f073-4ec2-98ab-743235303b64.png)

**Comment by rafluq** [comment]
That was exactly the problem. Thank you so much
