### ISSUE TITLE
GADEN_player - Filaments passing through walls

### ISSUE THREAD

**Issue by GhostMF123** [MAPIRlab/gaden#25]
In my GADEN_player simulation, the filaments are passing through my obstacles. The Photo below shows the inside of a wall where filaments can be seen passing; I also positioned a PID sensor inside of the wall just to make the issue clear.
![image](https://user-images.githubusercontent.com/111584934/209410168-61fdd02b-bc1a-4364-96df-126e90a85219.png)

I am working with a slightly older version of GADEN, however, when using the practice scenarios (on which I am basing my launch files) they don't seem to face the same issue (at least nowhere near to the same 'passing' extent).

My GADEN.launch file does not show filaments passing through the wall when doing the same basic visual inspection as was done in GADEN_player (Photo 2). I'm not entirely sure whether this narrows down the problem. 

![image](https://user-images.githubusercontent.com/111584934/209410041-869a61ed-562f-45f2-862d-04c217d727a7.png)

My occupancy files generated from the pre-processing seem fine (Onshape was used to create the COLLADA and STL files).

No errors appear in the terminal other than, "map" passed to lookupTransform argument target_frame does not exist._ 
, but this ceases shortly after it starts running
Have you experienced the same issue before in the past? Any help to solve this issue is much appreciated (I am new to ROS).

**Comment by PepeOjeda** [comment]
Hello. The markers generated by the player node are not actual filament positions, just a visual indicator. Meaning, they're not meant to be very precise, and are randomly distributed around the filaments. Even if the markers appear inside of an obstacle, things are ok.
