### ISSUE TITLE
Header File Missing

### ISSUE THREAD

**Issue by velonSigs** [MAPIRlab/gaden#32]
![image](https://github.com/MAPIRlab/gaden/assets/148208167/115b3ca4-dce0-4a69-a477-1a9ecfd4c4be)
![image](https://github.com/MAPIRlab/gaden/assets/148208167/b7361d4f-367f-4aaa-9c0a-0d7c1e00fc94)
it seems that "vec3.hpp" is not exist in ros1 project
how can i deal with this problem
thanks!

**Comment by PepeOjeda** [comment]
You need to do a recursive clone of the repository to get all the submodules with `git clone --recursive`.

Alternatively, if you already have it cloned, you can do `git submodule update --init` at the repository root.
