### ISSUE TITLE
catkin_make error in gaden

### ISSUE THREAD

**Issue by velonSigs** [MAPIRlab/gaden#33]
![image](https://github.com/MAPIRlab/gaden/assets/148208167/42f942e7-55ae-4745-ae07-5a9a100f4bfb)
![image](https://github.com/MAPIRlab/gaden/assets/148208167/bc380fd9-4bae-423d-ab4d-5e454e849287)
Hello!
When I tried to compile all the ROS packages included in Gaden (including the supplementary olfaction_msgs package), 
an error occurred during the compilation: 
The marchRay function defined at line 323 in DDA.h only accepts six parameters, but seven parameters were used when marchRay was called at line 145 in simulated_tadlas.cpp.
 The versions I downloaded are all corresponding to ROS1, and the system itself is ROS Melodic Ubuntu 18.0. 
Have you encountered this error during debugging? How did you solve it? thanks for replying.
![image](https://github.com/MAPIRlab/gaden/assets/148208167/280efd36-422f-43e1-b090-31c8bc491b3b)

**Comment by PepeOjeda** [comment]
I think you might have downloaded the latest version of the DDA library, rather than the one that was linked as a submodule? In any case, I've updated the code to use the most recent one, so it should be ok now.

**Comment by velonSigs** [comment]
thanks a lot!
it  works!
