### ISSUE TITLE
CAN'T FIND "coppelia_remote_api"

### ISSUE THREAD

**Issue by lvzhoujing** [MAPIRlab/gaden#38]
ROS2 gaden_preprocessing: CMakeLists.txt 35: list(APPEND AMENT_DEPS coppelia_remote_api)
I only find CoppeliaSim/programming/zmqRemoteApi and other romote api. There is no package names coppelia_remote_api.

**Comment by PepeOjeda** [comment]
Hello. The coppelia_remote_api package is available as part of the [Utils](https://github.com/MAPIRlab/utils/tree/ros2/Coppelia/coppelia_remote_api) repository, and is basically just an ament wrapper for the zmqRemoteApi library. You can also choose to disable the coppelia dependency in the CMakeLists of the preprocessing package, if you don't need it.
