### ISSUE TITLE
Missing file ''moveComppeliarobot.pp''

### ISSUE THREAD

**Issue by TaiE64** [MAPIRlab/gaden#43]
Hi, I encountered the following problem while building, how should I solve it?  Sorry for disturbing , I have very less experience with ROS2.
![image](https://github.com/MAPIRlab/gaden/assets/165344121/b98a111d-c035-4bf0-bf8d-e61aebd5172c)

**Comment by TaiE64** [comment]
Need help :(

**Comment by PepeOjeda** [comment]
Hello. There was an error in one of the CMakeLists files. It is fixed in the new version (2.4.0)
