### ISSUE TITLE
Missing file “gaden_common/third_party/DDA/include/DDA”

### ISSUE THREAD

**Issue by TaiE64** [MAPIRlab/gaden#45]
Hi, I tried to compile agian after update , but it still has some errors...
![image](https://github.com/MAPIRlab/gaden/assets/165344121/c3bd1203-5a71-4ed0-a0fe-552a6f81b28d)

**Comment by PepeOjeda** [comment]
The DDA package is a submodule of gaden. You need to either clone gaden with the `--recursive` option, or (if you already have cloned it) run `git submodule update --init --recursive` to get all the submodules.

**Comment by TaiE64** [comment]
> The DDA package is a submodule of gaden. You need to either clone gaden with the `--recursive` option, or (if you already have cloned it) run `git submodule update --init --recursive` to get all the submodules.

Thank you! I will try it again! :)
